### ISSUE TITLE
Script php artisan optimize handling the post-install-cmd event returned with error code 255

### ISSUE THREAD

**Issue by danilodorgam** [RachidLaasri/LaravelInstaller#110]
When I moved the laravel to the production server and ran the "`composer install`" command I came across this issue

Has anyone ever experienced this?
```
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postInstall
> php artisan optimize
PHP Warning:  Uncaught ErrorException: require(/var/www/html/gemeos-backend/vendor/rachidlaasri/laravel-installer/src/Providers/../routes/web.php): failed to open stream: No such file or directory in /var/www/html/gemeos-backend/vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php:71
Stack trace:
#0 /var/www/html/gemeos-backend/vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php(71): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'require(/var/ww...', '/var/www/html/g...', 71, Array)
#1 /var/www/html/gemeos-backend/vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php(71): require()
#2 /var/www/html/gemeos-backend/vendor/rachidlaasri/laravel-installer/src/Providers/LaravelInstallerServiceProvider.php(27): Illuminate\Support\ServiceProvider->loadRoutesFrom('/var/www/html/g...')
#3 /var/www/html/gemeos-backend/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(574): RachidLaasri\LaravelInstaller\Providers\LaravelInstallerServiceProvider->register( in /var/www/html/gemeos-backend/vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php on line 71
PHP Fatal error:  Illuminate\Support\ServiceProvider::loadRoutesFrom(): Failed opening required '/var/www/html/gemeos-backend/vendor/rachidlaasri/laravel-installer/src/Providers/../routes/web.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/gemeos-backend/vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php on line 71


  [Symfony\Component\Debug\Exception\FatalErrorException]
  Illuminate\Support\ServiceProvider::loadRoutesFrom(): Failed opening requir
  ed '/var/www/html/gemeos-backend/vendor/rachidlaasri/laravel-installer/src/
  Providers/../routes/web.php' (include_path='.:/usr/share/pear:/usr/share/ph
  p')

```

**Comment by ghyster** [comment]
I've experienced the same error, the "Routes" folder has to be renamed "routes"

**Comment by RachidLaasri** [comment]
Fixed.
